name: CI on multiple events

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      main

jobs:
  name: hello world
  runs_on: ubuntu-latest
  steps:
    name: "Echo basic information."
    run: |
      echo "Job ID: $GITHUB_JOB"
      echo "Action: $GITHUB_ACTION"
      echo "Actor: $GITHUB_ACTOR"